version: '3.8'

services:
  web:
    build: ./webapp
    command: python3 craft serve -p 8000 -b 0.0.0.0
    volumes:
      - ./webapp/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=masonite
      - POSTGRES_PASSWORD=masonite
      - POSTGRES_DB=masonite_dev

volumes:
  postgres_data_dev:
